language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
sudo: false
install: true
jdk: 
    - oraclejdk8

addons:
  sonarcloud:
    organization: "button-github" # the key of the org you chose at step #3
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'